### ISSUE TITLE
Parse as WireArray/Data returns error on PW 3.0.36

### ISSUE THREAD

**Issue by lesaff** [owzim/pw-fieldtype-yaml#1]
I got this error when I tried to parse YAML data as WireArray/Data

```
Error: Class 'WireData' not found (line 4 of /Users/rudy/Sites/pwdemo/public/site/modules/FieldtypeYaml/owzim/FieldtypeYaml/FTYData.php) 

This error message was shown because: you are logged in as a Superuser. Error has been logged.
```

**Comment by owzim** [comment]
Thanks for the report. Yeah it's not PW 3.x ready yet. I'll take care of it soon.

**Comment by owzim** [comment]
I added PW3 compatibility on the dev branch, could you please test if this works in your enviroment too?

**Comment by lesaff** [comment]
It works! Tested on PW 3.0.36 and 3.0.39
Thx

**Comment by owzim** [comment]
Awesome, thanks!
